import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import Navbar from "@/app/components/navbar";
import Footer from "@/app/components/footer";

const PPEditorialNew = localFont({
  src: [
    {
      path: './assets/fonts/PPEditorialNew/PPEditorialNew-Variable.woff2',
      style: 'normal',
    },
    {
      path: './assets/fonts/PPEditorialNew/PPEditorialNew-ItalicVariable.woff2',
      style: 'italic',
    },
  ],
  variable: '--font-pp-editorial-new',
  display: 'swap',
});

const PublicSans = localFont({
  src: [
    {
      path: './assets/fonts/PublicSans/PublicSans[wght].woff2',
      style: 'normal',
    },
    {
      path: './assets/fonts/PublicSans/PublicSans-Italic[wght].woff2',
      style: 'italic',
    },
  ],
  variable: '--font-public-sans',
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${PPEditorialNew.variable} ${PublicSans.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
